---
- name: install PostgreSQL
  ansible.builtin.apt:
    name: postgresql
    state: present
- name: open port for PostgreSQL using UFW
  community.general.ufw:
    rule: allow
    port: 5432
    proto: tcp
