---
- name: run all the roles for server web
  hosts: web
  become: true
  roles:
    - ansible_decker
- name: run all the roles for server db
  hosts: db
  become: true
  roles:
    - ansible_PostgreSQL
- name: run all the roles for server lb
  hosts: lb
  become: true
  roles:
  - ansible_nginx_lb
  
