name: Run Ansible Playbook Locally on Runner

on:
  push:
    paths: 'Ansible/**'
  pull_request:
    branches:
      - main

jobs:
  run_local_ansible:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: a
        run: echo -e "http {\n    upstream backend {\n        server \"localhost\";\n    }\n\n    server {\n        listen 80;\n\n        location / {\n            proxy_pass http://backend;\n        }\n    }\n}" > Ansible/roles/ansible_nginx_lb/templates/nginx.conf.j2 
        
      - name: Run Ansible Playbook on Localhost
        uses: dawidd6/action-ansible-playbook@v3
        with:
          playbook: Ansible/playbook.yml

          # Explicitly target localhost in your inventory
          inventory: |
            [db]
            localhost ansible_connection=local
            [web]
            localhost ansible_connection=local
            [lb]
            localhost ansible_connection=local

          
          args: ''
